language: python
cache: pip
python:
 - pypy
 - pypy3
 - 2.7
 - 3.4
 - 3.5
 - 3.6

# Use container-based infrastructure
sudo: false

install:
 - pip install coverage

script:
 - coverage run --source=olefile -m nose tests

after_success:
 - pip install coveralls
 - coveralls

after_script:
 - coverage report
 - pip install pycodestyle pyflakes
 - pyflakes .
 - pycodestyle --statistics --count .

matrix:
  fast_finish: true
